import React, { useState } from 'react';
import './ToSModal.css';

// Bump this version string whenever the ToS changes materially.
// Users who accepted an older version will be asked to re-accept.
const TOS_VERSION = '1.0.0';
const STORAGE_KEY = 'gfc-tos-accepted';

export function hasAcceptedToS(): boolean {
  try {
    return localStorage.getItem(STORAGE_KEY) === TOS_VERSION;
  } catch {
    return false;
  }
}

function acceptToS(): void {
  try {
    localStorage.setItem(STORAGE_KEY, TOS_VERSION);
  } catch {
    // localStorage unavailable — allow usage anyway
  }
}

interface ToSModalProps {
  onAccept: () => void;
  viewOnly?: boolean;
  onClose?: () => void;
}

const ToSModal: React.FC<ToSModalProps> = ({ onAccept, viewOnly = false, onClose }) => {
  const [checked, setChecked] = useState(false);

  const handleAccept = () => {
    if (!checked) return;
    acceptToS();
    onAccept();
  };

  const handleDecline = () => {
    // Redirect away from the app if the user declines
    window.location.href = 'https://weather.gov';
  };

  return (
    <div className="tos-backdrop" role="dialog" aria-modal="true" aria-labelledby="tos-title">
      <div className="tos-modal">

        <div className="tos-modal-header">
          <div className="tos-modal-header-row">
            <div>
              <h2 id="tos-title">Terms of Service</h2>
              <p>Please read and accept before using Graphical Forecast Creator &mdash; Effective March 1, 2026</p>
            </div>
            {viewOnly && (
              <button className="tos-close-view-btn" onClick={onClose} aria-label="Close">
                &times;
              </button>
            )}
          </div>
        </div>

        <div className="tos-modal-body">

          <h3>1. Unofficial Use &amp; Disclaimer (Critical)</h3>
          <p>
            GFC is intended solely as a <strong>creative and educational tool</strong>. It is <strong>NOT</strong> an official
            source of weather warnings, watches, or advisories. GFC is not affiliated with, endorsed by, or connected to the
            National Weather Service (NWS), the Storm Prediction Center (SPC), NOAA, or any government agency. All forecasts
            and graphics created within GFC are entirely unofficial. <strong>Do not use this app to make decisions that affect
            your safety, property, or the safety of others.</strong> Always consult official sources (e.g.,&nbsp;
            <a href="https://weather.gov" target="_blank" rel="noopener noreferrer">weather.gov</a>) for authoritative
            weather information.
          </p>

          <h3>2. User Responsibility &amp; Proper Use</h3>
          <p>You are fully and solely responsible for any graphics, forecasts, and discussions you create. You agree <strong>NOT</strong> to use GFC to:</p>
          <ul>
            <li>Create or distribute graphics intended to incite public panic or spread misinformation.</li>
            <li>Impersonate, replicate, or misrepresent official government products or agencies.</li>
            <li>Distribute forecasts without clearly labeling them as <em>"Unofficial"</em> or <em>"Experimental."</em></li>
            <li>Harass, threaten, or harm any individual or group.</li>
            <li>Violate any applicable local, state, federal, or international laws.</li>
          </ul>

          <h3>3. License to Use</h3>
          <p>
            You are granted a personal, non-exclusive, non-transferable, revocable license to use GFC for personal,
            educational, or non-commercial research purposes. Any content you generate remains your property. GFC does
            not claim ownership over your created content. You are solely responsible for how you share or distribute
            content created with the App.
          </p>

          <h3>4. Limitation of Liability</h3>
          <p>
            TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, the creator of GFC shall not be liable for any damages
            of any kind — including direct, indirect, incidental, special, or consequential damages — arising from your
            use of the App, actions taken based on content generated by the App, or errors in any data displayed. You
            expressly acknowledge that any reliance on GFC content for real-world safety decisions is entirely at your
            own risk.
          </p>

          <h3>5. "As-Is" Service</h3>
          <p>
            GFC is provided on an <strong>"As-Is"</strong> and <strong>"As-Available"</strong> basis without warranties
            of any kind. We do not guarantee uninterrupted, error-free, or secure operation, nor that any data
            (boundaries, storm reports, map layers) will be accurate or current.
          </p>

          <h3>6. Indemnification</h3>
          <p>
            You agree to indemnify and hold harmless the creator of GFC from any claims, damages, or expenses (including
            attorneys' fees) arising from your use of the App or violation of these Terms.
          </p>

          <h3>7. Modifications &amp; Termination</h3>
          <p>
            We may update these Terms at any time. Material changes will prompt re-acceptance. We reserve the right to
            suspend or terminate access for violations of these Terms without prior notice.
          </p>

          <h3>8. Governing Law</h3>
          <p>
            These Terms are governed by the laws of the State of Oklahoma, United States. Disputes are subject to the
            exclusive jurisdiction of courts in Oklahoma.
          </p>

          <h3>9. Contact</h3>
          <p>
            Questions? Reach out via the{' '}
            <a href="https://discord.gg/SGk37rg8sz" target="_blank" rel="noopener noreferrer">official GFC Support Discord</a>
            {' '}or on{' '}
            <a href="https://x.com/WeatherboySuper" target="_blank" rel="noopener noreferrer">X (@WeatherboySuper)</a>.
          </p>

        </div>

        {viewOnly ? (
          <div className="tos-modal-footer">
            <div className="tos-button-row">
              <button className="tos-btn-accept" onClick={onClose}>
                Close
              </button>
            </div>
          </div>
        ) : (
          <div className="tos-modal-footer">
            <label className="tos-checkbox-row">
              <input
                type="checkbox"
                checked={checked}
                onChange={(e) => setChecked(e.target.checked)}
              />
              I have read and agree to the Terms of Service. I understand that GFC is an unofficial educational tool
              and I will not rely on it for real-world safety decisions.
            </label>
            <div className="tos-button-row">
              <button className="tos-btn-decline" onClick={handleDecline}>
                Decline
              </button>
              <button className="tos-btn-accept" onClick={handleAccept} disabled={!checked}>
                Accept &amp; Continue
              </button>
            </div>
          </div>
        )}

      </div>
    </div>
  );
};

export default ToSModal;
