name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  deployments: write  # Add this permission for deployment status updates
  statuses: write     # Add this permission for commit status updates

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --no-fund --no-audit --loglevel=error

      - name: Build
        env:
          CI: ""  # Allow warnings in CI mode
        run: npm run build

      # Upload build artifacts to use in deploy jobs
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build
          retention-days: 1

  # Deploy to gh-pages when pushing to main
  deploy-production:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          branch: gh-pages

  # Deploy preview for pull requests
  deploy-preview:
    needs: build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: build

      # Create a deployment instead of using the PR preview action
      - name: Create GitHub Deployment
        id: deployment
        uses: bobheadxi/deployments@v1
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: pr-${{ github.event.pull_request.number }}
          ref: ${{ github.head_ref }}

      - name: Deploy PR to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build
          target-folder: pr-preview/pr-${{ github.event.pull_request.number }}
          branch: gh-pages
          clean-exclude: |
            pr-preview/!(pr-${{ github.event.pull_request.number }})
            !pr-preview

      # Update deployment status
      - name: Update Deployment Status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-preview/pr-${{ github.event.pull_request.number }}

      # Add a comment to the PR with the preview URL
      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            const previewUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/pr-preview/pr-${context.payload.pull_request.number}`;
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 PR Preview deployed!\n\nPreview: [${previewUrl}](${previewUrl})`
            });